### ISSUE TITLE
couldn't fetch data - no internet connection or API key

### ISSUE THREAD

**Issue by ossvn** [ravibpatel/SalesManager#1]
I'm using your app to track my sales.

But I couldn't fetch, as it's showing error, my internet connection is ok, API key is correct.

Can you please help me?

I'm using .net framework 5.5

**Comment by ossvn** [comment]
OK, I figured it out.

It does not create an app and use app API key, it's personal API key.

**Comment by ravibpatel** [comment]
@ossvn You need API key from https://build.envato.com as mentioned in documentation provided with the app.

**Comment by ravibpatel** [comment]
@ossvn Envato changed the API so the application may need an update. I will provide it soon.

**Comment by ravibpatel** [comment]
@ossvn Released version 1.0.6 with the fix.
